# Generated by Django 3.2.13 on 2022-10-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('order_type', models.CharField(max_length=128)),
                ('order_price', models.IntegerField()),
                ('order_quantity', models.IntegerField()),
                ('order_left_quantity', models.IntegerField(blank=True, null=True)),
                ('order_status', models.CharField(default='enqueued', max_length=16)),
            ],
            options={
                'db_table': 'orderHandler_orders',
            },
        ),
    ]
